services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: solar_estimator
    ports:
      - "5432:5432"
    volumes:
      - solar_pg:/var/lib/postgresql/data
volumes:
  solar_pg: {}
